chore: fix type check errors
This fixes the following warnings (displayed as errors):

```sh
> papupata-docs@1.0.2 type-check /Users/mikavilpas/git/papupata/packages/docs
> tsc

src/pages/guides/declaring/schemas.tsx(4,34): error TS6133: 'Examples' is declared but its value is never read.
src/pages/guides/declaring/schemas.tsx(6,10): error TS6133: 'FixedFont' is declared but its value is never read.
```